# Generated by Django 3.2.9 on 2021-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
