# Generated by Django 3.2.9 on 2021-11-24 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_direction_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_direction', to='restaurants.direction'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_type', to='restaurants.restaurant_types'),
        ),
    ]
