language: python

env:
    global:
      - PSQL_USERNAME=francisco
      - PSQL_PASS=jose_francisco123*
      - PSQL_DBNAME=prueba
      - PSQL_HOST=localhost
      - PSQL_PORT=5514

services:
    - postgresql
install:
    - pip install django djangorestframework djangorestframework-simplejwt PyJWT django-cors-headers psycopg2-binary
before_script:
  - psql -c "CREATE DATABASE prueba;" -U postgres
  - psql -c "CREATE USER francisco WITH PASSWORD 'jose_francisco123*';" -U postgres
  - psql -c "ALTER USER francisco CREATEDB;" -U postgres
  
script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test